export interface IndustryPreset {
  id: string;
  label: string;
  emoji: string;
  fields: Record<string, unknown>;
}

export const INDUSTRY_PRESETS: IndustryPreset[] = [
  {
    id: 'beauty',
    label: 'Beauty & Wellness',
    emoji: '💅',
    fields: {
      industry: 'beauty',
      brandVoice: 'elegant',
      emotionalTone: 'aspirational',
      atmosphere: 'luxury',
      luxuryLevel: 'premium',
      brandStyle: 'minimalist',
      primaryGoal: 'Drive appointment bookings and build a loyal client community',
      customerPainPoints: 'Inconsistent results, rushed appointments, stylists who don\'t listen to what clients actually want',
    },
  },
  {
    id: 'health',
    label: 'Health & Fitness',
    emoji: '🏃',
    fields: {
      industry: 'health',
      brandVoice: 'motivational',
      emotionalTone: 'empowering',
      atmosphere: 'energetic',
      luxuryLevel: 'quality',
      brandStyle: 'bold',
      primaryGoal: 'Convert website visitors into consultations or trial memberships',
      customerPainPoints: 'Tried other solutions that didn\'t stick, intimidated by gyms, unsure where to start',
    },
  },
  {
    id: 'legal',
    label: 'Legal Services',
    emoji: '⚖️',
    fields: {
      industry: 'legal',
      brandVoice: 'authoritative',
      emotionalTone: 'trustworthy',
      atmosphere: 'professional',
      luxuryLevel: 'premium',
      brandStyle: 'classic',
      primaryGoal: 'Generate qualified case inquiries and convert them into signed clients',
      customerPainPoints: 'Intimidated by legal processes, unsure of their rights, afraid of high costs',
    },
  },
  {
    id: 'home_services',
    label: 'Home Services',
    emoji: '🔧',
    fields: {
      industry: 'home_services',
      brandVoice: 'trustworthy',
      emotionalTone: 'reassuring',
      atmosphere: 'professional',
      luxuryLevel: 'quality',
      brandStyle: 'clean',
      primaryGoal: 'Drive estimate requests and build a reputation for reliability',
      customerPainPoints: 'Fear of contractor scams, uncertainty about pricing, stress of project coordination',
    },
  },
  {
    id: 'restaurant',
    label: 'Restaurant & Food',
    emoji: '🍽️',
    fields: {
      industry: 'restaurant',
      brandVoice: 'conversational',
      emotionalTone: 'heartfelt',
      atmosphere: 'artisan',
      luxuryLevel: 'quality',
      brandStyle: 'organic',
      primaryGoal: 'Fill reservation slots and grow private event and catering revenue',
      customerPainPoints: 'Generic dining experiences, unclear menus online, difficulty finding unique spots',
    },
  },
  {
    id: 'financial',
    label: 'Financial Services',
    emoji: '💼',
    fields: {
      industry: 'financial',
      brandVoice: 'authoritative',
      emotionalTone: 'trustworthy',
      atmosphere: 'professional',
      luxuryLevel: 'premium',
      brandStyle: 'minimalist',
      primaryGoal: 'Schedule discovery calls with qualified prospects',
      customerPainPoints: 'Confused by financial complexity, unsure if advisor has their best interests at heart',
    },
  },
  {
    id: 'technology',
    label: 'Technology & SaaS',
    emoji: '💻',
    fields: {
      industry: 'technology',
      brandVoice: 'innovative',
      emotionalTone: 'exciting',
      atmosphere: 'futuristic',
      luxuryLevel: 'quality',
      brandStyle: 'modern',
      primaryGoal: 'Drive free trial signups and product demo requests',
      customerPainPoints: 'Overwhelmed by too many tools, tired of software that promises more than it delivers',
    },
  },
  {
    id: 'ecommerce',
    label: 'E-Commerce & Retail',
    emoji: '🛍️',
    fields: {
      industry: 'ecommerce',
      brandVoice: 'conversational',
      emotionalTone: 'exciting',
      atmosphere: 'modern',
      luxuryLevel: 'quality',
      brandStyle: 'bold',
      primaryGoal: 'Drive product sales and grow repeat purchase rate',
      customerPainPoints: 'Decision fatigue, uncertain product quality, slow or expensive shipping',
    },
  },
  {
    id: 'real_estate',
    label: 'Real Estate',
    emoji: '🏡',
    fields: {
      industry: 'real_estate',
      brandVoice: 'trustworthy',
      emotionalTone: 'aspirational',
      atmosphere: 'luxury',
      luxuryLevel: 'premium',
      brandStyle: 'clean',
      primaryGoal: 'Generate buyer and seller leads and showcase listings',
      customerPainPoints: 'Overwhelmed by the market, uncertain which agent to trust, fear of overpaying or underselling',
    },
  },
  {
    id: 'education',
    label: 'Education & Coaching',
    emoji: '🎓',
    fields: {
      industry: 'education',
      brandVoice: 'motivational',
      emotionalTone: 'empowering',
      atmosphere: 'professional',
      luxuryLevel: 'quality',
      brandStyle: 'clean',
      primaryGoal: 'Drive course enrollments and discovery calls',
      customerPainPoints: 'Wasted money on courses that didn\'t deliver results, overwhelmed, unsure what to trust',
    },
  },
];
