export interface SampleBusiness {
  id: string;
  emoji: string;
  name: string;
  tagline: string;
  industry: string;
  priceLabel: string;
  city: string;
  description: string;
  data: Record<string, unknown>;
}

export const SAMPLE_BUSINESSES: SampleBusiness[] = [
  {
    id: 'luxe-beauty',
    emoji: '💅',
    name: 'Luxe Beauty Studio',
    tagline: 'Premium salon in Scottsdale, AZ',
    industry: 'beauty',
    priceLabel: 'Premium',
    city: 'Scottsdale, AZ',
    description: 'High-end hair & skin studio targeting affluent women 28–55',
    data: {
      businessName: 'Luxe Beauty Studio',
      tagline: 'Where Premium Care Meets Lasting Results',
      businessType: 'service',
      industry: 'beauty',
      city: 'Scottsdale',
      state: 'AZ',
      country: 'USA',
      targetAudience: 'Affluent women aged 28–55 who prioritize premium self-care experiences',
      audienceAge: '28–55',
      audienceIncome: '$100k+',
      audiencePainPoints: 'Tired of inconsistent results, rushed appointments, and stylists who don\'t listen to what they actually want',
      audienceDesires: 'Feel genuinely transformed, understood, and excited to show off their new look',
      audienceFears: 'Wasting money on a bad salon experience or trusting someone with their hair and being disappointed',
      audienceObjections: 'Is it worth the premium price? Will I actually get what I asked for?',
      primaryService: 'Precision haircuts and balayage color',
      secondaryServices: 'Keratin treatments, skin facials, lash extensions',
      uniqueValueProp: 'Complimentary hair health analysis with every service — we treat the root cause, not just the look',
      pricePoint: 'premium',
      resultsOrOutcomes: 'Clients leave feeling genuinely transformed and already excited to rebook',
      desiredAtmosphere: 'luxurious_refined',
      desiredBrandStyle: 'luxury_boutique',
      desiredEmotionalTone: 'inspiring_aspirational',
      luxuryLevel: 5,
      brandColors: ['#C9A84C', '#1A1F36', '#f59e0b', '#9ca3af'],
      brandPersonality: ['sophisticated', 'luxurious', 'approachable'],
      brandVoice: 'professional',
      serviceRadius: 'Scottsdale and surrounding Maricopa County',
      ctaPreference: 'Book Your Transformation',
      primaryGoal: 'generate_bookings',
      socialLinks: { instagram: '', facebook: '', linkedin: '', tiktok: '', youtube: '', twitter: '' },
      testimonials: [],
      reviews: [],
      competitors: [],
      services: [],
      locationsServed: [],
      isMultiLocation: false,
      additionalNotes: '4.9-star average across 380+ Google reviews; featured in Phoenix Magazine Best Of 2023',
    },
  },
  {
    id: 'peak-pt',
    emoji: '🏃',
    name: 'Peak Performance PT',
    tagline: 'Sports physical therapy in Austin, TX',
    industry: 'health',
    priceLabel: 'Mid-Market',
    city: 'Austin, TX',
    description: 'Sports-focused PT clinic helping athletes return to full performance',
    data: {
      businessName: 'Peak Performance Physical Therapy',
      tagline: 'Get Back to the Sport You Love',
      businessType: 'service',
      industry: 'health',
      city: 'Austin',
      state: 'TX',
      country: 'USA',
      targetAudience: 'Active adults and athletes aged 18–50 recovering from injury or preventing one',
      audienceAge: '18–50',
      audienceIncome: '$60k–$120k',
      audiencePainPoints: 'Frustrated with generic cookie-cutter PT that doesn\'t actually fix the problem and keeps them off the field longer',
      audienceDesires: 'Return to their sport stronger and faster than before, with a clear recovery roadmap',
      audienceFears: 'Chronic re-injury, being sidelined permanently, or wasting money on ineffective treatment',
      audienceObjections: 'Will this actually work? Do I need a referral? How long will it take?',
      primaryService: 'Post-surgical rehab and sports injury recovery',
      secondaryServices: 'Dry needling, movement screening, return-to-sport programs',
      uniqueValueProp: '90% of our patients return to full sport activity — backed by evidence-based protocols and one-on-one hands-on care every visit',
      pricePoint: 'mid_market',
      resultsOrOutcomes: 'Get back to playing the sport they love pain-free and with confidence',
      desiredAtmosphere: 'bold_energetic',
      desiredBrandStyle: 'modern_minimalist',
      desiredEmotionalTone: 'confident_empowering',
      luxuryLevel: 3,
      brandColors: ['#E8610A', '#1C1C1E', '#f59e0b', '#9ca3af'],
      brandPersonality: ['energetic', 'trustworthy', 'innovative'],
      brandVoice: 'authoritative',
      serviceRadius: 'Austin metro and Cedar Park',
      ctaPreference: 'Start Your Recovery',
      primaryGoal: 'generate_leads',
      socialLinks: { instagram: '', facebook: '', linkedin: '', tiktok: '', youtube: '', twitter: '' },
      testimonials: [],
      reviews: [],
      competitors: [],
      services: [],
      locationsServed: [],
      isMultiLocation: false,
      additionalNotes: 'Official PT partner of Austin FC youth academy; 200+ competitive athletes treated',
    },
  },
  {
    id: 'apex-law',
    emoji: '⚖️',
    name: 'Apex Law Group',
    tagline: 'Personal injury law firm in Chicago, IL',
    industry: 'legal',
    priceLabel: 'Premium',
    city: 'Chicago, IL',
    description: 'Aggressive personal injury attorneys fighting for maximum settlements',
    data: {
      businessName: 'Apex Law Group',
      tagline: 'Fighting for the Compensation You Deserve',
      businessType: 'service',
      industry: 'legal',
      city: 'Chicago',
      state: 'IL',
      country: 'USA',
      targetAudience: 'Injury victims aged 25–60 seeking fair compensation after accidents or negligence',
      audienceAge: '25–60',
      audienceIncome: 'Mixed — working class to middle income',
      audiencePainPoints: 'Overwhelmed after an injury, don\'t know their rights, afraid of big insurance companies lowballing them',
      audienceDesires: 'Get maximum compensation quickly and have someone powerful fighting in their corner',
      audienceFears: 'Being taken advantage of by insurance companies or choosing the wrong attorney and losing their case',
      audienceObjections: 'Can I afford a lawyer? What if I lose? How long does this take?',
      primaryService: 'Personal injury and car accident claims',
      secondaryServices: 'Slip & fall, medical malpractice, workplace injury, wrongful death',
      uniqueValueProp: 'Our clients receive 3x the average settlement — and we never charge unless you win',
      pricePoint: 'premium',
      resultsOrOutcomes: 'Walk away with maximum compensation and feel justice was served',
      desiredAtmosphere: 'clean_minimal',
      desiredBrandStyle: 'classic_timeless',
      desiredEmotionalTone: 'confident_empowering',
      luxuryLevel: 4,
      brandColors: ['#1B2A6B', '#C41E3A', '#f59e0b', '#9ca3af'],
      brandPersonality: ['trustworthy', 'bold', 'sophisticated'],
      brandVoice: 'authoritative',
      serviceRadius: 'Chicago and all of Illinois',
      ctaPreference: 'Get Your Free Case Review',
      primaryGoal: 'generate_leads',
      socialLinks: { instagram: '', facebook: '', linkedin: '', tiktok: '', youtube: '', twitter: '' },
      testimonials: [],
      reviews: [],
      competitors: [],
      services: [],
      locationsServed: [],
      isMultiLocation: false,
      additionalNotes: '$47M recovered for clients; Super Lawyers rated; 5-star reviews from 500+ clients',
    },
  },
  {
    id: 'homeshield-roofing',
    emoji: '🏠',
    name: 'HomeShield Roofing',
    tagline: 'Residential roofing in Denver, CO',
    industry: 'home_services',
    priceLabel: 'Mid-Market',
    city: 'Denver, CO',
    description: 'Storm damage and full replacement roofing with insurance claim expertise',
    data: {
      businessName: 'HomeShield Roofing',
      tagline: 'Your Roof. Protected. Guaranteed.',
      businessType: 'service',
      industry: 'home_services',
      city: 'Denver',
      state: 'CO',
      country: 'USA',
      targetAudience: 'Denver homeowners aged 35–65 dealing with storm damage or aging roofs',
      audienceAge: '35–65',
      audienceIncome: '$75k–$150k',
      audiencePainPoints: 'Stressed about cost, unsure about insurance coverage, afraid of contractor scams and being overcharged',
      audienceDesires: 'A new roof handled from start to finish with zero stress and maximum insurance payout',
      audienceFears: 'Getting scammed, paying out of pocket when insurance should cover it, contractor disappearing mid-job',
      audienceObjections: 'How do I know I can trust you? Will insurance actually pay? How long will this take?',
      primaryService: 'Storm damage repair and full roof replacement',
      secondaryServices: 'Insurance claim navigation, gutters, skylights',
      uniqueValueProp: 'Our dedicated insurance claim specialist ensures you get every dollar you\'re owed — at zero cost to you',
      pricePoint: 'mid_market',
      resultsOrOutcomes: 'A brand-new roof with little to no out-of-pocket cost and confidence it will last 30 years',
      desiredAtmosphere: 'clean_minimal',
      desiredBrandStyle: 'corporate_pro',
      desiredEmotionalTone: 'calm_reassuring',
      luxuryLevel: 3,
      brandColors: ['#1565C0', '#F9A825', '#f59e0b', '#9ca3af'],
      brandPersonality: ['trustworthy', 'approachable'],
      brandVoice: 'professional',
      serviceRadius: 'Denver metro and Front Range communities',
      ctaPreference: 'Get My Free Inspection',
      primaryGoal: 'generate_leads',
      socialLinks: { instagram: '', facebook: '', linkedin: '', tiktok: '', youtube: '', twitter: '' },
      testimonials: [],
      reviews: [],
      competitors: [],
      services: [],
      locationsServed: [],
      isMultiLocation: false,
      additionalNotes: '1,200+ roofs installed; A+ BBB rating; 4.8 stars on Google from 620 reviews',
    },
  },
  {
    id: 'harvest-kitchen',
    emoji: '🍽️',
    name: 'Harvest Kitchen',
    tagline: 'Farm-to-table restaurant in Portland, OR',
    industry: 'restaurant',
    priceLabel: 'Mid-Market',
    city: 'Portland, OR',
    description: 'Seasonal farm-to-table dining with locally sourced ingredients',
    data: {
      businessName: 'Harvest Kitchen',
      tagline: 'From Oregon Farms to Your Table',
      businessType: 'local_business',
      industry: 'restaurant',
      city: 'Portland',
      state: 'OR',
      country: 'USA',
      targetAudience: 'Food-conscious diners aged 28–55 who value local sourcing and exceptional seasonal flavor',
      audienceAge: '28–55',
      audienceIncome: '$70k–$130k',
      audiencePainPoints: 'Bored of the same restaurant experiences and skeptical of \'farm-to-table\' marketing that\'s just a buzzword',
      audienceDesires: 'A genuinely memorable dining experience they\'ll tell friends about and return to every season',
      audienceFears: 'Overpaying for a disappointing meal or being misled by false sustainability claims',
      audienceObjections: 'Is it really farm-to-table or just a marketing claim? Is it worth the price?',
      primaryService: 'Farm-to-table dinner service',
      secondaryServices: 'Sunday brunch, private dining events, cooking classes, wine pairings',
      uniqueValueProp: 'Our menu changes every week — built entirely around what\'s freshest from 12 local Oregon farms',
      pricePoint: 'mid_market',
      resultsOrOutcomes: 'A memorable meal they\'ll tell friends about and want to repeat every season',
      desiredAtmosphere: 'warm_inviting',
      desiredBrandStyle: 'rustic_earthy',
      desiredEmotionalTone: 'warm_empathetic',
      luxuryLevel: 3,
      brandColors: ['#5C4033', '#7CB342', '#f59e0b', '#9ca3af'],
      brandPersonality: ['approachable', 'calming', 'trustworthy'],
      brandVoice: 'friendly',
      serviceRadius: 'Portland, OR (Alberta Arts District)',
      ctaPreference: 'Reserve Your Table',
      primaryGoal: 'drive_reservations',
      socialLinks: { instagram: '', facebook: '', linkedin: '', tiktok: '', youtube: '', twitter: '' },
      testimonials: [],
      reviews: [],
      competitors: [],
      services: [],
      locationsServed: [],
      isMultiLocation: false,
      additionalNotes: 'Featured in Eater PDX; James Beard semifinalist chef; 4.9 stars on Yelp from 880 reviews',
    },
  },
  {
    id: 'clarity-financial',
    emoji: '💼',
    name: 'Clarity Financial Advisors',
    tagline: 'Fee-only financial planning in Nashville, TN',
    industry: 'financial',
    priceLabel: 'Premium',
    city: 'Nashville, TN',
    description: 'Fiduciary wealth management for professionals and families',
    data: {
      businessName: 'Clarity Financial Advisors',
      tagline: 'Financial Confidence Without the Conflicts',
      businessType: 'service',
      industry: 'financial',
      city: 'Nashville',
      state: 'TN',
      country: 'USA',
      targetAudience: 'High-earning professionals and families with $250k–$2M in investable assets',
      audienceAge: '35–65',
      audienceIncome: '$200k+',
      audiencePainPoints: 'Uncertain their advisor is actually on their side; overwhelmed by financial complexity and hidden fees',
      audienceDesires: 'Total clarity and confidence in their financial future with an advisor who has no conflicts of interest',
      audienceFears: 'Losing retirement savings, being misled by commission-driven advisors, making irreversible financial mistakes',
      audienceObjections: 'How is fee-only different? Are you worth the cost compared to my current advisor?',
      primaryService: 'Comprehensive financial planning and investment management',
      secondaryServices: 'Tax optimization, retirement planning, estate coordination',
      uniqueValueProp: 'As fee-only fiduciaries we never earn commissions — our clients save an average of $47k in hidden fees over 10 years',
      pricePoint: 'premium',
      resultsOrOutcomes: 'Clarity and confidence in their financial future with a trusted advisor they can call anytime',
      desiredAtmosphere: 'luxurious_refined',
      desiredBrandStyle: 'modern_minimalist',
      desiredEmotionalTone: 'trustworthy_reliable',
      luxuryLevel: 4,
      brandColors: ['#0D2B6B', '#00897B', '#f59e0b', '#9ca3af'],
      brandPersonality: ['trustworthy', 'sophisticated', 'innovative'],
      brandVoice: 'professional',
      serviceRadius: 'Nashville and virtual clients nationwide',
      ctaPreference: 'Schedule Your Discovery Call',
      primaryGoal: 'generate_leads',
      socialLinks: { instagram: '', facebook: '', linkedin: '', tiktok: '', youtube: '', twitter: '' },
      testimonials: [],
      reviews: [],
      competitors: [],
      services: [],
      locationsServed: [],
      isMultiLocation: false,
      additionalNotes: 'NAPFA member; CFP certified; $180M+ AUM; featured in Forbes and Nashville Business Journal',
    },
  },
];
