export interface SampleBusiness {
  id: string;
  emoji: string;
  name: string;
  tagline: string;
  industry: string;
  priceLabel: string;
  city: string;
  description: string;
  data: Record<string, unknown>;
}

export const SAMPLE_BUSINESSES: SampleBusiness[] = [
  {
    id: 'luxe-beauty',
    emoji: '💅',
    name: 'Luxe Beauty Studio',
    tagline: 'Premium salon in Scottsdale, AZ',
    industry: 'beauty',
    priceLabel: 'Premium',
    city: 'Scottsdale, AZ',
    description: 'High-end hair & skin studio targeting affluent women 28–55',
    data: {
      businessName: 'Luxe Beauty Studio',
      businessType: 'Beauty & Wellness Salon',
      industry: 'beauty',
      location: 'Scottsdale, AZ',
      targetAudience: 'Affluent women aged 28–55 who prioritize premium self-care experiences',
      primaryGoal: 'Book high-value appointments and build a loyal client base',
      uniqueValueProposition: 'Complimentary hair health analysis with every service — we treat the root cause, not just the look',
      pricePoint: 'premium',
      primaryColor: '#C9A84C',
      secondaryColor: '#1A1F36',
      brandPersonality: 'Sophisticated, warm, and results-focused',
      brandVoice: 'elegant',
      emotionalTone: 'aspirational',
      atmosphere: 'luxury',
      luxuryLevel: 'ultra_premium',
      brandStyle: 'minimalist',
      mainServices: 'Precision haircuts, balayage color, keratin treatments, skin facials, lash extensions',
      serviceArea: 'Scottsdale and surrounding Maricopa County',
      competitorDifferentiator: 'Unlike chain salons, every stylist has 10+ years experience and we limit bookings to maintain quality',
      customerPainPoints: 'Tired of inconsistent results, rushed appointments, and stylists who don\'t listen',
      desiredOutcome: 'Clients leave feeling genuinely transformed and already excited to rebook',
      socialProof: '4.9-star average across 380+ Google reviews; featured in Phoenix Magazine\'s Best Of 2023',
      callToAction: 'Book Your Transformation',
      websiteGoal: 'Drive online bookings and showcase portfolio',
    },
  },
  {
    id: 'peak-pt',
    emoji: '🏃',
    name: 'Peak Performance PT',
    tagline: 'Sports physical therapy in Austin, TX',
    industry: 'health',
    priceLabel: 'Mid-Market',
    city: 'Austin, TX',
    description: 'Sports-focused PT clinic helping athletes return to full performance',
    data: {
      businessName: 'Peak Performance Physical Therapy',
      businessType: 'Sports Physical Therapy Clinic',
      industry: 'health',
      location: 'Austin, TX',
      targetAudience: 'Active adults and athletes aged 18–50 recovering from injury or preventing one',
      primaryGoal: 'Fill the schedule with high-intent patients and build physician referral relationships',
      uniqueValueProposition: '90% of our patients return to full sport activity — backed by evidence-based protocols and hands-on care',
      pricePoint: 'mid_market',
      primaryColor: '#E8610A',
      secondaryColor: '#1C1C1E',
      brandPersonality: 'Energetic, credible, and deeply invested in patient outcomes',
      brandVoice: 'authoritative',
      emotionalTone: 'motivational',
      atmosphere: 'professional',
      luxuryLevel: 'quality',
      brandStyle: 'bold',
      mainServices: 'Post-surgical rehab, sports injury recovery, dry needling, movement screening, return-to-sport programs',
      serviceArea: 'Austin metro and Cedar Park',
      competitorDifferentiator: 'One-on-one sessions every visit — no techs, no shortcuts, same therapist each time',
      customerPainPoints: 'Frustrated with generic cookie-cutter PT that doesn\'t actually fix the problem',
      desiredOutcome: 'Get back to playing the sport they love pain-free and with confidence',
      socialProof: 'Worked with 200+ competitive athletes; official PT partner of Austin FC youth academy',
      callToAction: 'Start Your Recovery',
      websiteGoal: 'Generate patient inquiries and build physician referral pipeline',
    },
  },
  {
    id: 'apex-law',
    emoji: '⚖️',
    name: 'Apex Law Group',
    tagline: 'Personal injury law firm in Chicago, IL',
    industry: 'legal',
    priceLabel: 'Premium',
    city: 'Chicago, IL',
    description: 'Aggressive personal injury attorneys fighting for maximum settlements',
    data: {
      businessName: 'Apex Law Group',
      businessType: 'Personal Injury Law Firm',
      industry: 'legal',
      location: 'Chicago, IL',
      targetAudience: 'Injury victims aged 25–60 seeking fair compensation after accidents or negligence',
      primaryGoal: 'Generate qualified case inquiries and convert them into signed clients',
      uniqueValueProposition: 'Our clients receive 3x the average settlement — and we never charge unless you win',
      pricePoint: 'premium',
      primaryColor: '#1B2A6B',
      secondaryColor: '#C41E3A',
      brandPersonality: 'Fierce, trustworthy, and relentlessly client-focused',
      brandVoice: 'authoritative',
      emotionalTone: 'empowering',
      atmosphere: 'professional',
      luxuryLevel: 'premium',
      brandStyle: 'classic',
      mainServices: 'Car accident claims, slip & fall, medical malpractice, workplace injury, wrongful death',
      serviceArea: 'Chicago and all of Illinois',
      competitorDifferentiator: 'We take fewer cases so every client gets a senior attorney — not a paralegal',
      customerPainPoints: 'Overwhelmed after an injury, don\'t know their rights, afraid of big insurance companies',
      desiredOutcome: 'Walk away with maximum compensation and feel justice was served',
      socialProof: '$47M recovered for clients; Super Lawyers rated; 5-star reviews from 500+ clients',
      callToAction: 'Get Your Free Case Review',
      websiteGoal: 'Convert visitors into case inquiry form submissions',
    },
  },
  {
    id: 'homeshield-roofing',
    emoji: '🏠',
    name: 'HomeShield Roofing',
    tagline: 'Residential roofing in Denver, CO',
    industry: 'home_services',
    priceLabel: 'Mid-Market',
    city: 'Denver, CO',
    description: 'Storm damage and full replacement roofing with insurance claim expertise',
    data: {
      businessName: 'HomeShield Roofing',
      businessType: 'Residential Roofing Contractor',
      industry: 'home_services',
      location: 'Denver, CO',
      targetAudience: 'Denver homeowners aged 35–65 dealing with storm damage or aging roofs',
      primaryGoal: 'Generate estimate requests and close projects through insurance claim support',
      uniqueValueProposition: 'Our dedicated insurance claim specialist ensures you get every dollar you\'re owed — at zero cost to you',
      pricePoint: 'mid_market',
      primaryColor: '#1565C0',
      secondaryColor: '#F9A825',
      brandPersonality: 'Reliable, transparent, and homeowner-first',
      brandVoice: 'trustworthy',
      emotionalTone: 'reassuring',
      atmosphere: 'professional',
      luxuryLevel: 'quality',
      brandStyle: 'clean',
      mainServices: 'Storm damage repair, full roof replacement, insurance claim navigation, gutters, skylights',
      serviceArea: 'Denver metro and Front Range communities',
      competitorDifferentiator: 'We handle the insurance paperwork — most homeowners get a new roof with little to no out-of-pocket',
      customerPainPoints: 'Stressed about cost, unsure about insurance coverage, afraid of contractor scams',
      desiredOutcome: 'A brand-new roof without the headache and confidence it will last 30 years',
      socialProof: '1,200+ roofs installed; A+ BBB rating; 4.8 stars on Google from 620 reviews',
      callToAction: 'Get My Free Inspection',
      websiteGoal: 'Drive free inspection requests and build trust with homeowners',
    },
  },
  {
    id: 'harvest-kitchen',
    emoji: '🍽️',
    name: 'Harvest Kitchen',
    tagline: 'Farm-to-table restaurant in Portland, OR',
    industry: 'restaurant',
    priceLabel: 'Mid-Market',
    city: 'Portland, OR',
    description: 'Seasonal farm-to-table dining with locally sourced ingredients',
    data: {
      businessName: 'Harvest Kitchen',
      businessType: 'Farm-to-Table Restaurant',
      industry: 'restaurant',
      location: 'Portland, OR',
      targetAudience: 'Food-conscious diners aged 28–55 who value local sourcing and exceptional flavor',
      primaryGoal: 'Fill reservation slots, grow private event bookings, and build a loyal community',
      uniqueValueProposition: 'Our menu changes every week — built entirely around what\'s freshest from 12 local Oregon farms',
      pricePoint: 'mid_market',
      primaryColor: '#5C4033',
      secondaryColor: '#7CB342',
      brandPersonality: 'Warm, artisanal, and community-rooted',
      brandVoice: 'conversational',
      emotionalTone: 'heartfelt',
      atmosphere: 'artisan',
      luxuryLevel: 'quality',
      brandStyle: 'organic',
      mainServices: 'Dinner service, Sunday brunch, private dining events, cooking classes, wine pairings',
      serviceArea: 'Portland, OR (Alberta Arts District)',
      competitorDifferentiator: 'We publish our farm partners on the menu — radical transparency about where your food comes from',
      customerPainPoints: 'Bored of the same restaurant experiences, unsure if "farm-to-table" claims are real',
      desiredOutcome: 'A memorable meal they\'ll tell friends about and want to repeat every season',
      socialProof: 'Featured in Eater PDX; James Beard semifinalist chef; 4.9 stars on Yelp from 880 reviews',
      callToAction: 'Reserve Your Table',
      websiteGoal: 'Drive OpenTable reservations and private event inquiries',
    },
  },
  {
    id: 'clarity-financial',
    emoji: '💼',
    name: 'Clarity Financial Advisors',
    tagline: 'Fee-only financial planning in Nashville, TN',
    industry: 'financial',
    priceLabel: 'Premium',
    city: 'Nashville, TN',
    description: 'Fiduciary wealth management for professionals and families',
    data: {
      businessName: 'Clarity Financial Advisors',
      businessType: 'Fee-Only Financial Planning Firm',
      industry: 'financial',
      location: 'Nashville, TN',
      targetAudience: 'High-earning professionals and families with $250k–$2M in investable assets',
      primaryGoal: 'Schedule discovery calls with qualified prospects and build long-term AUM',
      uniqueValueProposition: 'As fee-only fiduciaries we never earn commissions — our clients save an average of $47k in hidden fees over 10 years',
      pricePoint: 'premium',
      primaryColor: '#0D2B6B',
      secondaryColor: '#00897B',
      brandPersonality: 'Transparent, sophisticated, and genuinely client-centric',
      brandVoice: 'elegant',
      emotionalTone: 'trustworthy',
      atmosphere: 'luxury',
      luxuryLevel: 'premium',
      brandStyle: 'minimalist',
      mainServices: 'Comprehensive financial planning, investment management, tax optimization, retirement planning, estate coordination',
      serviceArea: 'Nashville and virtual clients nationwide',
      competitorDifferentiator: 'Fee-only fiduciary — no products to sell, no conflicts of interest, ever',
      customerPainPoints: 'Uncertain their advisor is actually on their side; overwhelmed by financial complexity',
      desiredOutcome: 'Clarity and confidence in their financial future with a trusted advisor they can call anytime',
      socialProof: 'NAPFA member; CFP certified; $180M+ AUM; featured in Forbes and Nashville Business Journal',
      callToAction: 'Schedule Your Discovery Call',
      websiteGoal: 'Generate qualified discovery call bookings with high-net-worth prospects',
    },
  },
];
